### ISSUE TITLE
How to add parameters into appium block?

### ISSUE THREAD

**Issue by Dento55** [zasadnyy/appium-gradle-plugin#2]
appium {
	--log-timestamp
	--local-timezone
	--no-reset
}

**Comment by zasadnyy** [comment]
Plugin do not support parameters

**Comment by zasadnyy** [comment]
But you can modify plugin to make it work for you:
https://github.com/zasadnyy/appium-gradle-plugin/blob/master/plugin/src/main/groovy/com/zasadnyy/gradle/appium/AppiumPlugin.groovy#L66
