### ISSUE TITLE
How to add Appium location for Windows?

### ISSUE THREAD

**Issue by Dento55** [zasadnyy/appium-gradle-plugin#3]
I tried start server, but plugins seems not find the appium.

12:50:44.827 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
12:50:44.827 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:50:44.827 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':startAppiumServer'.
12:50:44.828 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > The file you provided was not found on your HDD. You provided the following file path: C:\usr\local\bin\node

**Comment by zasadnyy** [comment]
You have to have appium installed and added to the PATH
